# Generated by Django 4.1.4 on 2022-12-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.SmallIntegerField()),
                ('family', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('second', models.CharField(blank=True, max_length=20, null=True)),
                ('pasport', models.CharField(blank=True, max_length=120, null=True)),
                ('born', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=20, null=True)),
                ('clientname', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
