# Generated by Django 4.1.4 on 2022-12-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_tblaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblaccount',
            name='account',
            field=models.SmallIntegerField(verbose_name='имя автора'),
        ),
        migrations.AlterField(
            model_name='tblaccount',
            name='born',
            field=models.DateTimeField(blank=True, null=True, verbose_name='имя born'),
        ),
        migrations.AlterField(
            model_name='tblaccount',
            name='clientname',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='имя clientname'),
        ),
        migrations.AlterField(
            model_name='tblaccount',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='имя datetime'),
        ),
        migrations.AlterField(
            model_name='tblaccount',
            name='family',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='имя family'),
        ),
        migrations.AlterField(
            model_name='tblaccount',
            name='hostname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='имя hostname'),
        ),
        migrations.AlterField(
            model_name='tblaccount',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='имя name'),
        ),
        migrations.AlterField(
            model_name='tblaccount',
            name='pasport',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='имя pasport'),
        ),
        migrations.AlterField(
            model_name='tblaccount',
            name='second',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='имя second'),
        ),
        migrations.AlterField(
            model_name='tblaccount',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='имя username'),
        ),
    ]
