# Generated by Django 4.1.4 on 2023-01-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_tblaccount_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblAccount',
        ),
    ]
